import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

// dummy
const Header = () => <div className='text-2xl px-2 py-1 bg-blue-600'>Header</div>;
const Navigation = () => <div className='text-2xl px-2 py-1 bg-yellow-400'>Navigation</div>;
const Footer = () => <div className='text-2xl px-2 py-1 bg-red-600'>Footer</div>;

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja">
      <body>
        <Header />
        <Navigation />
        {children}
        <Footer />
      </body>
    </html>
  )
}
